services:
  passbolt:
    image: alpine:latest
    container_name: sistema_passbolt
    command: tail -f /dev/null
    ports:
      - "8080:80"
    networks:
      - red-monitoreo

  chkmonitor:
    image: alpine:latest
    container_name: sistema_chkmonitor
    command: tail -f /dev/null
    networks:
      - red-monitoreo

  db-master:
    image: mariadb:10.5
    container_name: db_maestro
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    networks:
      - red-monitoreo

  db-slave:
    image: mariadb:10.5
    container_name: db_esclavo
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3307:3306"
    networks:
      - red-monitoreo

networks:
  red-monitoreo:
    driver: bridge
